// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pessoa.proto
// Protobuf Java Version: 4.27.2

package com.example.tarefaprotocl.protos;

public interface ListaPessoasOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tarefaprotocol.ListaPessoas)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tarefaprotocol.Pessoa pessoas = 1;</code>
   */
  java.util.List<Pessoa>
      getPessoasList();
  /**
   * <code>repeated .tarefaprotocol.Pessoa pessoas = 1;</code>
   */
  Pessoa getPessoas(int index);
  /**
   * <code>repeated .tarefaprotocol.Pessoa pessoas = 1;</code>
   */
  int getPessoasCount();
  /**
   * <code>repeated .tarefaprotocol.Pessoa pessoas = 1;</code>
   */
  java.util.List<? extends PessoaOrBuilder>
      getPessoasOrBuilderList();
  /**
   * <code>repeated .tarefaprotocol.Pessoa pessoas = 1;</code>
   */
  PessoaOrBuilder getPessoasOrBuilder(
      int index);
}
