// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pessoa.proto
// Protobuf Java Version: 4.27.2

package com.example.tarefaprotocl.protos;

public final class PessoaProtos {
  private PessoaProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      PessoaProtos.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tarefaprotocol_Pessoa_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tarefaprotocol_Pessoa_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tarefaprotocol_ListaPessoas_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tarefaprotocol_ListaPessoas_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014pessoa.proto\022\016tarefaprotocol\"\342\002\n\006Pesso" +
      "a\022\014\n\004nome\030\001 \001(\t\022\r\n\005idade\030\002 \001(\005\0222\n\004type\030\003" +
      " \001(\0162$.tarefaprotocol.Pessoa.TipoSangion" +
      "eo\"\206\002\n\rTipoSangioneo\022\"\n\036TIPO_SANGUINEO_N" +
      "AOESPECIFICADO\020\000\022\025\n\021TIPO_SANGUINEO_AP\020\001\022" +
      "\025\n\021TIPO_SANGUINEO_AN\020\002\022\025\n\021TIPO_SANGUINEO" +
      "_BP\020\003\022\025\n\021TIPO_SANGUINEO_BN\020\004\022\025\n\021TIPO_SAN" +
      "GUINEO_OP\020\005\022\025\n\021TIPO_SANGUINEO_ON\020\006\022\026\n\022TI" +
      "PO_SANGUINEO_ABP\020\007\022\026\n\022TIPO_SANGUINEO_ABN" +
      "\020\010\022\027\n\023TIPO_SANGUINEO_NULL\020\t\"7\n\014ListaPess" +
      "oas\022\'\n\007pessoas\030\001 \003(\0132\026.tarefaprotocol.Pe" +
      "ssoaB2\n com.example.tarefaprotocl.protos" +
      "B\014PessoaProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tarefaprotocol_Pessoa_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tarefaprotocol_Pessoa_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tarefaprotocol_Pessoa_descriptor,
        new java.lang.String[] { "Nome", "Idade", "Type", });
    internal_static_tarefaprotocol_ListaPessoas_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tarefaprotocol_ListaPessoas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tarefaprotocol_ListaPessoas_descriptor,
        new java.lang.String[] { "Pessoas", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
